<?php
$config['bangs']=array(
	'!ddg'=>'https://duckduckgo.com/?q=',
	'!gi'=>'https://www.google.fr/search?hl=fr&tbm=isch&biw=6366&bih=6628&q=',
	'!q'=>'https://www.qwant.com/?q=',
	'!qi'=>'https://www.qwant.com/?t=images&q=',
);
$config['alternatives']=array(
	'DDG'=>'https://duckduckgo.com/?q=',
	'SearX'=>'https://www.framabee.org/?q=',
	'Qwant'=>'https://www.qwant.com/?q=',
);
